var Observer=function(){function a(a,b){return b.priority-a.priority}function b(a){return void 0===a?!0:null===a}var g;g=function h(){if(!(this instanceof h))return new h;this._channelSubscribers={}};g.prototype.subscribe=function(h,d,f){var e=this._channelSubscribers[h];b(e)&&(e=[]);if(b(f)){f=e;var c,k,m=0;if(!b(f))for(k=f.length,c=0;c<k;c++)0>f[c].priority&&f[c].priority<m&&(m=f[c].priority);f=m-1}e.push({priority:f,callback:d});e=e.sort(a);this._channelSubscribers[h]=e};g.prototype.unsubscribe=
function(a,d){var f,e=this._channelSubscribers[a];if(!b(e)){for(f=0;f<e.length;f++)if(e[f].callback===d){e.splice(f,1);break}0===e.length&&delete this._channelSubscribers[a]}};g.prototype.publish=function(a,d,f,e){var c,k,m,g=null;if(0===arguments.length||b(a))throw Error("channelId argument required.");1<arguments.length&&(g=Array.prototype.slice.call(arguments,1));m=this._channelSubscribers[a];k={channelId:a,cancel:!1};if(b(m))return!0;for(c=0;c<m.length;c++)if(m[c].callback.apply(k,g),k.cancel)return!1;
return!0};return g}();var dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};
(function(a){function b(a){return void 0===a?!0:null===a}a.isNullOrUndefined=b;a.areSameDot=function(a,l){return b(a)&&b(l)?!0:b(a)!==b(l)?!1:a.x===l.x&&a.y===l.y};a.getRandom=function(a,b){return a+Math.floor(Math.random()*(b-a+1))};a.getRandomItem=function(b){var l;l=a.getRandom(0,b.length-1);return b[l]};a.inherit=function(){var a=function(){};return function(b,h){a.prototype=h.prototype;b.prototype=new a;b.uber=h.prototype;b.prototype.constructor=b}}()})(dotBox.utility);dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};dotBox.utility.line=dotBox.utility.line||{};
(function(a){function b(a){return 0<Math.abs(a.d1.x-a.d2.x)}a.isHLine=b;a.getBoxesFromLine=function(a,l,h){var d=l-1,f=[],e,c;b(a)?(e=a.d1.y,c=Math.min(a.d1.x,a.d2.x),0!==a.d1.y&&(a.d1.y!==h-1&&f.push(e*d+c),e-=1)):(c=a.d1.x,e=Math.min(a.d1.y,a.d2.y),0!==a.d1.x&&(a.d1.x!==l-1&&f.push(e*d+c),c-=1));f.push(e*d+c);return f};a.getLinesFromBox=function(a,b){var h=b-1,d=[],f;f=a%h;h=(a-f)/h;d.push({d1:{x:f,y:h},d2:{x:f+1,y:h}});d.push({d1:{x:f+1,y:h},d2:{x:f+1,y:h+1}});d.push({d1:{x:f,y:h+1},d2:{x:f+1,
y:h+1}});d.push({d1:{x:f,y:h},d2:{x:f,y:h+1}});return d}})(dotBox.utility.line);dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};dotBox.utility.iterators=dotBox.utility.iterators||{};
(function(a){a.hLineIterator=function(a,g){function l(){return f?!1:{d1:{x:h,y:d},d2:{x:h+1,y:d}}}var h=-1,d=0,f=!1;return{next:function(){if(f)return null;if(d===g-1&&h===a-2)return f=!0,null;h===a-2?(d+=1,h=0):h+=1;return l()},current:l}};a.vLineIterator=function(a,g){function l(){return f?!1:{d1:{x:h,y:d},d2:{x:h,y:d+1}}}var h=-1,d=0,f=!1;return{next:function(){if(f)return null;if(d===g-2&&h===a-1)return f=!0,null;h===a-1?(d+=1,h=0):h+=1;return l()},current:l}}})(dotBox.utility.iterators);dotBox=dotBox||{};
dotBox.boxState=function(a,b){function g(){return f.length}function l(a){var c=g();if(0>a)throw new RangeError("boxIndex must be greater or equal to 0.");if(a>=c)throw new RangeError("boxIndex must be less than the box count ("+c+").");}function h(a){l(a);return null!==f[a]}function d(a){l(a);return f[a]}var f;(function(a,c){var k,b=(a-1)*(c-1);f=[];for(k=0;k<b;k++)f[k]=null})(a,b);return{getBoxCount:g,areAllBoxesScored:function(){return f.every(function(a){return null!==a})},isBoxScored:h,isBoxNotScored:function(a){return!h(a)},
whichPlayerScoredBox:d,scoreBox:function(a,c){l(a);f[a]=c},getCurrentScores:function(a){var c,k=[],b;for(c=0;c<a;c++)k[c]=0;a=g();for(c=0;c<a;c++)h(c)&&(b=d(c),k[b]+=1);return k},getPlayerBoxes:function(a){var c,k,b=[],f;k=g();for(c=0;c<k;c++)f=d(c),f===a&&b.push(c);return b}}};dotBox=dotBox||{};
dotBox.lineState=function(a,b){function g(c,k){var b,e;if(h.isNullOrUndefined(c))throw Error("line is null or undefined");l(c.d1,"line.d1");l(c.d2,"line.d2");e=Math.abs(c.d1.x-c.d2.x);b=Math.abs(c.d1.y-c.d2.y);if(1<e)throw new RangeError("Move appears to be too long on x-axis.  Line must only connect adjacent points.");if(1<b)throw new RangeError("Move appears to be too long on y-axis.  Line must only connect adjacent points.");if(1<e+b)throw new RangeError("Movement appears to be diagonal this is not allowed.");var p;
h.line.isHLine(c)?(e=d,b=c.d1.y,p=Math.min(c.d1.x,c.d2.x),b=b*(a-1)+p):(e=f,b=Math.min(c.d1.y,c.d2.y),p=c.d1.x,b=b*a+p);h.isNullOrUndefined(k)||k&&(e[b]=!0);return e[b]}function l(c,k){if(h.isNullOrUndefined(c))throw Error(k+" is null or undefined.");if(0>c.x)throw new RangeError(k+".x must be > 0.");if(c.x>=a)throw new RangeError(k+".x must be < "+a);if(0>c.y)throw new RangeError(k+".y must be > 0.");if(c.y>=b)throw new RangeError(k+".y must be < "+b);}var h=dotBox.utility,d=[],f=[],e;e={connected:g,
isBoxClosed:function(c){var b;b=h.line.getLinesFromBox(c,a);for(c=0;4>c;c++)if(!g(b[c]))return!1;return!0},getAllLinesForDot:function(c){var k=[],f,d;f=function(){return{x:c.x,y:c.y}};d=function(a,c){k.push({d1:f(),d2:{x:a,y:c}})};0<c.y&&d(c.x,c.y-1);c.x<a-1&&d(c.x+1,c.y);c.y<b-1&&d(c.x,c.y+1);0<c.x&&d(c.x-1,c.y);return k},getOpenLinesForDot:function(a){return e.getAllLinesForDot(a).filter(function(a){return!e.connected(a)})},getTotalLineCount:function(){return f.length+d.length},getLineStatesForBox:function(c){var b=
[],f=[],d,h;c=dotBox.utility.line.getLinesFromBox(c,a);for(d=0;4>d;d++)h=c[d],e.connected(h)?f.push(h):b.push(h);return{open:b,closed:f}}};(function(a,b){var e,h,p;h=(a-1)*b;p=(b-1)*a;for(e=0;e<h;e++)d[e]=!1;for(e=0;e<p;e++)f[e]=!1})(a,b);return e};dotBox=dotBox||{};
dotBox.gameEngine=function(a){function b(){return g()?null:k}function g(){return n.areAllBoxesScored()}var l=dotBox.utility,h,d,f,e,c,k,m,n=null;(function(a){a||(a={});d=l.isNullOrUndefined(a.dotCountLength)?10:parseInt(a.dotCountLength,10);f=l.isNullOrUndefined(a.dotCountWidth)?10:parseInt(a.dotCountWidth,10);h=l.isNullOrUndefined(a.playerCount)?2:parseInt(a.playerCount,10);k=l.isNullOrUndefined(a.startPlayer)?0:parseInt(a.startPlayer,10);if(isNaN(d))throw new TypeError("dotCountLength is not a number.");if(isNaN(f))throw new TypeError("dotCountWidth is not a number.");
if(isNaN(h))throw new TypeError("playerCount is not a number.");if(isNaN(k))throw new TypeError("startPlayer is not a number.");if(3>d)throw new RangeError("dotCountLength must be three or more");if(3>f)throw new RangeError("dotCountWidth must be three or more");if(2>h)throw new RangeError("playerCount must two or more");if(0>k||k>=h)throw new RangeError("startPlayer must be between 0 and playerCount-1");e=d-1;c=f-1;n=l.isNullOrUndefined(a.boxState)?dotBox.boxState(d,f):a.boxState;m=l.isNullOrUndefined(a.lineState)?
dotBox.lineState(d,f):a.lineState})(a);return{getDotCountLength:function(){return d},getBoxCountLength:function(){return e},getDotCountWidth:function(){return f},getBoxCountWidth:function(){return c},getBoxCount:function(){return e*c},getPlayerCount:function(){return h},getCurrentPlayer:b,getCurrentScores:function(){return n.getCurrentScores(h)},isLineConnected:function(a){return m.connected(a)},connectLine:function(a){var c={},e;if(g())throw Error("Cannot make a move when the game is over.");if(m.connected(a))throw Error("This line is already connected.");
e=b();m.connected(a,!0);a=l.line.getBoxesFromLine(a,d,f).filter(m.isBoxClosed).filter(n.isBoxNotScored);a.forEach(function(a){n.scoreBox(a,e)});c.boxesScored=a;c.gameOver=g();0===c.boxesScored.length?(a=g()?null:k=k===h-1?0:k+1,c.nextPlayer=a):c.nextPlayer=b();return c},isGameOver:g,hasAnyOpenLines:function(a){if(void 0===a)throw Error("dot argument was not supplied.");if(null===a)throw Error("dot argument was null.");return 0<m.getOpenLinesForDot(a).length},canConnectDots:function(a,c){var b,f,d;
if(l.isNullOrUndefined(a))throw Error("dot1 argument was null or undefined.");if(l.isNullOrUndefined(c))throw Error("dot2 argument was null or undefined.");f=m.getOpenLinesForDot(a);for(b=0;b<f.length;b++)if(d=f[b].d2,l.areSameDot(d,c))return!0;return!1},getPlayerBoxes:function(){return n.getPlayerBoxes.apply(n,arguments)},getOpenLinesForDot:function(){return m.getOpenLinesForDot.apply(m,arguments)},getTotalLineCount:function(){return m.getTotalLineCount.apply(m,arguments)},isBoxScored:function(){return n.isBoxScored.apply(n,
arguments)},getLineStatesForBox:function(){return m.getLineStatesForBox.apply(m,arguments)}}};dotBox=dotBox||{};
dotBox.model=function(a,b){var g=dotBox.utility,l;return l={selectedDot:null,hoveredDot:null,isSelectedDot:function(a){return null!==l.selectedDot&&g.areSameDot(a,l.selectedDot)},isHoveredDot:function(a){return null!==l.hoveredDot&&g.areSameDot(a,l.hoveredDot)},getDotColCount:function(){return a.getDotCountLength()},canConnectDots:function(b){return null!==l.selectedDot&&a.canConnectDots(l.selectedDot,b)},getDotRowCount:function(){return a.getDotCountWidth()},hasAnyOpenLines:function(b){return a.hasAnyOpenLines(b)},getCurrentScores:function(){return a.getCurrentScores()},
getCurrentPlayer:function(){return a.getCurrentPlayer()},getPlayerBoxes:function(){return a.getPlayerBoxes.apply(a,arguments)},gameConfig:b,isQuickStarting:!1}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};dotBox.views.constants={P1_COLOR:"#A4E402",P2_COLOR:"#BF7AFF",PX_COLOR:"#5B5B5B",SCORE_TXT_COLOR:"#E7F8F2",BOARD_BACK_COLOR:"#272822"};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.viewContext=function(a,b){var g,l;function h(a){for(var f in a)a.hasOwnProperty(f)&&(a[f]*=b);return a}var d=dotBox.utility,f,e;if(d.isNullOrUndefined(a))throw Error("observer parameter is required.");if(d.isNullOrUndefined(b))throw Error("pixelRatio is required.");l=g=0;e=h({DOT_RADIUS:5,DOT_MARGIN:20,POINT_FONT_SIZE:13,SCORE_BOARD_HEIGHT:65});a.subscribe("view.reserveCanvasSize",function(a){d.isNullOrUndefined(a)||(d.isNullOrUndefined(a.height)||(g+=a.height),d.isNullOrUndefined(a.width)||
(l+=a.width))});return f={observer:a,pixelRatio:b,stage:null,boxShapes:{},pixelSizes:e,initCanvasStage:function(a){var d;d=0;for(var e=null,h,p;null===e;)h="dotBoxCanvas_"+d,p=$("#"+h),0===p.length&&(e=h),d+=1;d=e;a.append('<canvas id="'+d+'" width='+l+" height="+g+' style="width: '+1/b*l+"px; height: "+1/b*g+'px;"></canvas>');f.stage=new createjs.Stage(d)},scalePixel:function(a){return a*b},scaleAllPixelProps:h,setDrawColors:function(a){var b=a.fillColor;a=a.strokeColor;dotBox.utility.isNullOrUndefined(b)||
(this.fillStyle=b.toString());dotBox.utility.isNullOrUndefined(a)||(this.strokeStyle=a.toString())},width:function(){if(null===f.stage)throw Error("stage has not been initialized; call initCanvasStage first.");return f.stage.canvas.width},height:function(){if(null===f.stage)throw Error("stage has not been initialized; call initCanvasStage first.");return f.stage.canvas.height},getPlayerColor:function(a){switch(a){case 0:return dotBox.views.constants.P1_COLOR;case 1:return dotBox.views.constants.P2_COLOR;
default:return dotBox.views.constants.PX_COLOR}}}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.Color=function(){function a(a){var b,e,c;b=parseInt(a.slice(1,3),16);e=parseInt(a.slice(3,5),16);a=parseInt(a.slice(5,7),16);c=new h;c.red=b;c.green=e;c.blue=a;return c}function b(a){var b,e,c,k;a=a.trim();a=a.toLowerCase();a=a.slice(5,a.length-1);a=a.trim();c=a.split(",");if(4!==c.length)throw Error("Could not parse rgba() color string.");a=parseInt(c[0].trim(),10);b=parseInt(c[1].trim(),10);e=parseInt(c[2].trim(),10);c=parseFloat(c[3].trim());k=new h;k.red=a;k.green=b;k.blue=e;k.alpha=
c;return k}function g(a){var b,e,c;a=a.trim();a=a.toLowerCase();a=a.slice(4,a.length-1);a=a.trim();e=a.split(",");if(3!==e.length)throw Error("Could not parse rgb() color string.");a=parseInt(e[0].trim(),10);b=parseInt(e[1].trim(),10);e=parseInt(e[2].trim(),10);c=new h;c.red=a;c.green=b;c.blue=e;return c}function l(d){d=d.trim();if(0===d.lastIndexOf("#",0)&&7===d.length)return a(d);if(0===d.lastIndexOf("rgba(",0))return b(d);if(0===d.lastIndexOf("rgb(",0))return g(d);throw Error("Invalid arguments.");
}var h;h=function f(a){var b;if(!(this instanceof f))return f.apply(new f,arguments);this.green=this.blue=this.red=255;this.alpha=1;if(1===arguments.length)return b=a.toString(),l(b);if(4===arguments.length){var k=arguments,m,g,p;b=Math.round(parseFloat(k[0]));m=Math.round(parseFloat(k[1]));g=Math.round(parseFloat(k[2]));p=parseFloat(k[3]);k=new h;k.red=b;k.green=m;k.blue=g;k.alpha=p;return k}if(3===arguments.length)return g=arguments,b=Math.round(parseFloat(g[0])),m=Math.round(parseFloat(g[1])),
k=Math.round(parseFloat(g[2])),g=new h,g.red=b,g.green=m,g.blue=k,g;if(0!==arguments.length)throw Error(arguments.length+" number of arguments not supported.");};h.parseHexColorString=a;h.parseColorString=l;h.parseRgbaColorString=b;h.parseRgbColorString=g;h.prototype.toString=function(){var a,b,c;a=Math.round(this.red);b=Math.round(this.green);c=Math.round(this.blue);return"rgba("+[a,b,c,this.alpha].join()+")"};h.prototype.clone=function(){var a=new h;a.red=this.red;a.green=this.green;a.blue=this.blue;
a.alpha=this.alpha;return a};return h}();dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.board=function(a,b){function g(b){u.isNullOrUndefined(b)||a.observer.publish("dotRollOver",b)}function l(b){u.isNullOrUndefined(b)||a.observer.publish("dotRollOut",b)}function h(){B||d(this.dot)}function d(b){a.observer.publish("dotClick",b)}function f(){var a=E,c=q(2.5*t.DOT_RADIUS);u.areSameDot(a,c)||(B||(!u.isNullOrUndefined(c)&&b.hasAnyOpenLines(c)?e("pointer"):e("")),E=c,B||(l(a),g(c)))}function e(b){a.stage.canvas.style.cursor=b}function c(){a.stage.update()}function k(c){var f,
e;c instanceof createjs.Shape?(f=c,c=f.dot,e=!0):(f=m(c),e=!1);c=b.isSelectedDot(c)?H:b.isHoveredDot(c)&&b.canConnectDots(c)?C:b.isHoveredDot(c)?I:J;c=new F(c);e?(f.fillColor=c,f.graphics.beginFill(c).inject(a.setDrawColors,f).drawCircle(0,0,t.DOT_RADIUS).endFill()):createjs.Tween.get(f.fillColor,{override:!0}).to(c,250);return f}function m(a){return D[a.y][a.x]}function n(c,f,e){var k,d=m(c.d1),h=m(c.d2),g=!1,l=a.scalePixel(1),n=null,t;k=r(c);u.isNullOrUndefined(k)?(k=new createjs.Shape,w(c,k),g=
!0):k.graphics.clear();k.graphics.setStrokeStyle(l).beginStroke(f).moveTo(d.x,d.y).lineTo(h.x,h.y);t=b.isQuickStarting;g&&(y.isHLine(c)?(k.scaleX=0.1,k.x=d.x-0.1*d.x,n={scaleX:1,x:0}):(k.scaleY=0.1,k.y=d.y-0.1*d.y,n={scaleY:1,y:0}),k.on("click",p),a.stage.addChild(k),createjs.Tween.get(k,{override:!0}).to(n,300).call(function(){var b;t||e||(b=new createjs.Shape,b.graphics.setStrokeStyle(a.scalePixel(1)).beginStroke(A).drawCircle(0,0,a.pixelSizes.DOT_RADIUS),b.x=h.x,b.y=h.y,b.scaleX=0,b.scaleY=0,a.stage.addChild(b),
createjs.Tween.get(b).to({scaleX:1.5,scaleY:1.5},150).to({scaleX:5,scaleY:5,alpha:0},1E3,createjs.Ease.sineOut).call(function(){a.stage.removeChild(b)}))}))}function p(b){b=a.stage.getObjectsUnderPoint(b.stageX,b.stageY).filter(function(a){return!u.isNullOrUndefined(a.dot)});0<b.length&&h.apply(b[0])}function x(c,f){var k,e,d,h;b.isQuickStarting||(e=m(c.lines[0].d1),h=m(c.lines[0].d2),k=e.x+(h.x-e.x)/2,e=m(c.lines[1].d1),h=m(c.lines[1].d2),e=e.y+(h.y-e.y)/2,d=new createjs.Text("+"+f,t.POINT_FONT_SIZE+
"px Helvetica",G.SCORE_TXT_COLOR),d.x=k,d.y=e,d.textAlign="center",d.textBaseline="middle",d.alpha=0,a.stage.addChild(d),createjs.Tween.get(d,{override:!1}).wait(550).to({alpha:1},0).to({alpha:0,y:a.height()+a.scalePixel(50)},3E3,createjs.Ease.sineOut).call(function(){a.stage.removeChild(d)}),createjs.Tween.get(d,{override:!1}).wait(550).to({scaleX:1.5,scaleY:1.5},200,createjs.Ease.elasticInOut))}function w(a,b){var c,f;c=s(a);f=c.store[c.y];u.isNullOrUndefined(f)&&(f={},c.store[c.y]=f);f[c.x]=b}
function r(a){var b;a=s(a);if(!a.store.hasOwnProperty(a.y))return null;b=a.store[a.y];return b.hasOwnProperty(a.x)?b[a.x]:null}function s(a){var b,c;u.line.isHLine(a)?(c=K,b=a.d1.y,a=Math.min(a.d1.x,a.d2.x)):(c=L,b=Math.min(a.d1.y,a.d2.y),a=a.d1.x);return{x:a,y:b,store:c}}function v(a,b){var c;c=Math.floor((a-t.DOT_MARGIN/2)/(2*t.DOT_RADIUS+t.DOT_MARGIN));return 0>c||c>=b?null:c}function q(c){var f,e,k,d;f=a.stage.mouseX;e=a.stage.mouseY;if(!a.stage.mouseInBounds)return null;k=v(f,b.getDotColCount());
if(null===k)return null;d=v(e,b.getDotRowCount());if(null===d)return null;k={x:k,y:d};d=m(k);var h=d.y;f=Math.pow(d.x-f,2)+Math.pow(h-e,2);c=Math.pow(c,2);f<=c||(k=null);return k}var u=dotBox.utility,y=dotBox.utility.line,G=dotBox.views.constants,F=dotBox.views.Color;if(u.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(u.isNullOrUndefined(b))throw Error("model is null or undefined.");var t=a.pixelSizes,J="#53d2f1",I="#89E0F5",H="#fc1f70",C="#E20355",A="white",D,K={},L={},
z,E=null,B=!1;(function(){var c,f,k;c={height:0,width:0};f=2*b.getDotColCount()*t.DOT_RADIUS;k=(b.getDotColCount()+1)*t.DOT_MARGIN;c.width=f+k;f=2*b.getDotRowCount()*t.DOT_RADIUS;k=(b.getDotRowCount()+1)*t.DOT_MARGIN;c.height=f+k;a.observer.publish("view.reserveCanvasSize",c)})();a.observer.subscribe("startGame",function(){var e,d,m,g=b.getDotRowCount(),l=b.getDotColCount(),n;e=new createjs.Shape;e.graphics.beginFill(G.BOARD_BACK_COLOR).drawRect(0,0,a.width(),a.height());a.stage.addChild(e);D=[];
for(d=0;d<g;d++)for(e=0;e<l;e++)0===e&&(n=[],D.push(n)),m=new createjs.Shape,m.dot={x:e,y:d},k(m),m.x=e*(t.DOT_MARGIN+2*t.DOT_RADIUS)+(t.DOT_MARGIN+t.DOT_RADIUS),m.y=d*(t.DOT_MARGIN+2*t.DOT_RADIUS)+(t.DOT_MARGIN+t.DOT_RADIUS),m.on("click",h),n.push(m),a.stage.addChild(m);a.stage.update();a:{g=20;z&&(clearInterval(z),z=null);if(null===g)g=20;else if(0>=g)break a;z=setInterval(f,1E3/Math.min(50,g))}createjs.Ticker.addEventListener("tick",c);createjs.Ticker.setFPS(60)});a.observer.subscribe("view.dotRollOver",
function(a){a=k(a);createjs.Tween.get(a,{override:!0}).to({scaleX:2,scaleY:2},150)});a.observer.subscribe("view.dotRollOut",function(a){a=k(a);createjs.Tween.get(a,{override:!0}).to({scaleX:1,scaleY:1},150)});a.observer.subscribe("view.dotSelectionChanged",function(a,b){var c;null!==a&&k(a);null!==b&&k(b);a!==b&&(c=m(null!==b?b:a),createjs.Tween.get(c,{override:!0}).to({scaleX:1,scaleY:1},150).call(function(){var a=q(t.DOT_RADIUS);u.isNullOrUndefined(a)&&e("")}))});a.observer.subscribe("view.lineConnected",
function(a,b){var c;k(a.d1);c=k(a.d2);createjs.Tween.get(c,{override:!0}).to({scaleX:1,scaleY:1},150);n(a,A,b)});a.observer.subscribe("view.boxesScored",function(b,c){var f;for(f=0;f<b.length;f++){var e=b[f],k=c,d=void 0,h=void 0,g=d=void 0,l=void 0,n=void 0,t=void 0,g=void 0,y=a.scalePixel(10),q=a.scalePixel(1),t=a.getPlayerColor(k),n=new F(t);n.alpha=0.33;n=n.toString();h=m(e.lines[0].d1);d=m(e.lines[1].d2);g=d.x-h.x;l=d.y-h.y;d=new createjs.Shape;d.graphics.setStrokeStyle(q).beginStroke(t).beginFill(n).drawRect(h.x,
h.y,g,l);g=(g+y)/g;d.scaleX=g;d.scaleY=g;d.x=-1*(h.x*g-h.x)-y/2;d.y=-1*(h.y*g-h.y)-y/2;d.upperLeft={x:h.x,y:h.y};d.alpha=0;d.on("click",p);a.stage.addChild(d);a.boxShapes[e.box]=d;createjs.Tween.get(d,{override:!0}).wait(350).to({alpha:1},0).to({x:0,y:0,scaleX:1,scaleY:1},350)}x(b[0],b.length)});a.observer.subscribe("startRemoteTurn",function(a){e("wait");B=!0});a.observer.subscribe("endRemoteTurn",function(a,b){var c=u.getRandom(700,1250),f=u.getRandom(170,750),k=u.getRandom(500,750),h=u.getRandom(Math.floor(75),
750);setTimeout(function(){g(b.d1);setTimeout(function(){d(b.d1);l(b.d1);setTimeout(function(){g(b.d2);setTimeout(function(){B=!1;e(null);d(b.d2);l(b.d2)},h)},k)},f)},c)});a.observer.subscribe("stopGame",function(){createjs.Ticker.removeEventListener("tick",c);z&&(clearInterval(z),z=null)});return{}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.score=function(a,b){function g(b,d){var h=new createjs.Container,g,l=a.scalePixel(1),w=a.scalePixel(2),u=a.scalePixel(9),C=a.scalePixel(6),A=a.scalePixel(13);g=new createjs.Shape;g.graphics.setStrokeStyle(l).beginStroke(x).beginFill(p).drawRoundRect(0,0,q.SCORE_BOX_W,d,w);h.addChild(g);g=new createjs.Text("0",q.SCORE_FONT_SIZE+"px Helvetica",f.SCORE_TXT_COLOR);g.x=q.SCORE_BOX_W/2;g.y=C+d/2;g.textAlign="center";g.textBaseline="middle";h.addChild(g);c.push(g);g=new createjs.Shape;g.graphics.setStrokeStyle(l).beginFill(r).beginStroke(s).arc(q.SCORE_BOX_W/
2,d+A,q.SCORE_BOX_W/4,Math.PI+0.25*Math.PI,1.75*Math.PI);g.alpha=0;k.push(g);h.addChild(g);l=g=new createjs.Shape;w=Math.round(0.3*d);C=a.scalePixel(2);A=a.scalePixel(2);l.fillColor=new e(v);l.strokeColor=new e(v);l.graphics.setStrokeStyle(C).beginStroke(v).beginFill(v).inject(a.setDrawColors,l).drawRoundRect(0,0,q.SCORE_BOX_W,w,A).endFill();h.addChild(g);m.push(g);g=new createjs.Text(b,q.P_NAME_FONT_SIZE+"px Helvetica",f.SCORE_TXT_COLOR);g.x=q.SCORE_BOX_W/2;g.y=u;g.textAlign="center";g.textBaseline=
"middle";n.push(g);h.addChild(g);return h}function l(a){var b,c,d,e,g;for(b=0;b<k.length;b++)c=k[b],b===a?(createjs.Tween.get(c,{override:!0}).to({alpha:1},250,createjs.Ease.sineIn),c=f.SCORE_TXT_COLOR):(createjs.Tween.get(c,{override:!0}).to({alpha:0},250,createjs.Ease.sineOut),c=w),g=m[b],d=h("fill",b,a),e=h("stroke",b,a),createjs.Tween.get(g.fillColor,{override:!0}).to(d,200),createjs.Tween.get(g.strokeColor,{override:!0}).to(e,200),n[b].color=c}function h(a,b,c){b===c?(b=0===b?new e(f.P1_COLOR):
new e(f.P2_COLOR),"fill"===a&&(b.alpha=0.33)):b=new e(v);return b}var d=dotBox.utility,f=dotBox.views.constants,e=dotBox.views.Color,c=[],k=[],m=[],n=[],p="#272822",x="#3b3d38",w="#a69b9d",r="#fc1f70",s="#E20355",v="#40403d",q=a.scaleAllPixelProps({SCORE_BOX_W:75,SCORE_FONT_SIZE:25,P_NAME_FONT_SIZE:10}),u=a.pixelSizes.SCORE_BOARD_HEIGHT;if(d.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(d.isNullOrUndefined(b))throw Error("model is null or undefined.");a.observer.publish("view.reserveCanvasSize",
{height:u});a.observer.subscribe("startGame",function(){var d,f,e=a.scalePixel(10);f=a.scalePixel(5);var h=u-2*f;d=a.height()-u;f=d+f+1;c=[];k=[];m=[];n=[];var p,x=a.scalePixel(1),w=a.height(),r=a.width();p=new createjs.Shape;p.graphics.beginLinearGradientFill(["#5b5b5b","#545454"],[0,1],0,d,0,w).drawRect(0,d,r,w).endFill();p.graphics.setStrokeStyle(x).beginStroke("#323232").moveTo(0,d).lineTo(r,d).endStroke();p.graphics.setStrokeStyle(x).beginStroke("#7d7d7d").moveTo(0,d+x).lineTo(r,d+x).endStroke();
a.stage.addChild(p);d=g(b.gameConfig.playerNames[0],h);d.x=e;d.y=f;a.stage.addChild(d);d=g(b.gameConfig.playerNames[1],h);d.x=a.width()-e-q.SCORE_BOX_W;d.y=f;a.stage.addChild(d);l(b.getCurrentPlayer())});a.observer.subscribe("gameOver",function(a){l(a)});a.observer.subscribe("view.boxesScored",function(){var a,d;d=b.getCurrentScores();for(a=0;a<d.length;a++)c[a].text=d[a]});a.observer.subscribe("views.playerTurnChanged",function(){l(b.getCurrentPlayer())});return{}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.gameOver=function(a,b){function g(b,d,h){var g,l,r,s,v,q=a.scalePixel(10),u=a.scalePixel(2),y;g=new createjs.Container;r=a.height()-k.SCORE_BOARD_HEIGHT;s=a.width();l=new createjs.Text(b,c+"px Helvetica",e.SCORE_TXT_COLOR);l.textAlign="center";l.textBaseline="middle";v=l.getBounds();b=v.height+2*q+2*u;q=v.width+2*q+2*u;v=new createjs.Shape;v.graphics.beginFill(e.BOARD_BACK_COLOR).drawRect(0,0,q,b);g.addChild(v);y=new f(d);y.alpha=0.2;v=new createjs.Shape;v.graphics.setStrokeStyle(u).beginStroke(d).beginFill(y.toString()).drawRect(0,
0,q,b);g.addChild(v);l.x=q/2;l.y=b/2;g.addChild(l);g.x=s/2;g.y=r/2;d=(s-q)/2;r=(r-b)/2;g.alpha=0;g.scaleX=0;g.scaleY=0;a.stage.addChild(g);createjs.Tween.get(g,{override:!0}).wait(h).to({alpha:1,scaleX:1,scaleY:1,x:d,y:r},1E3,createjs.Ease.quadIn).wait(2500).to({x:s+q/2},500,createjs.Ease.quadOut).call(function(){a.stage.removeChild(g)})}function l(b,c,d){var e,k,h=a.scalePixel(1);b=a.boxShapes[b];k=a.getPlayerColor(c);e=new f(k);e.alpha=0.33;e=e.toString();c=new createjs.Shape;c.graphics.setStrokeStyle(h).beginStroke(k).beginFill(e).drawRect(b.upperLeft.x,
b.upperLeft.y,d,d);c.upperLeft={x:b.upperLeft.x,y:b.upperLeft.y};return c}function h(c,f){var e,g,w,r,s,v,q;e=b.getPlayerBoxes(c);0!==e.length&&(s=2*k.DOT_RADIUS+k.DOT_MARGIN,e=e[d.getRandom(0,e.length-1)],q=l(e,c,s),g=a.scalePixel(15),e=(s+g)/s,w=-1*(q.upperLeft.x*e-q.upperLeft.x)-g/2,g=-1*(q.upperLeft.y*e-q.upperLeft.y)-g/2,r=a.scalePixel(45),s=(s+r)/s,v=-1*(q.upperLeft.x*s-q.upperLeft.x)-r/2,r=-1*(q.upperLeft.y*s-q.upperLeft.y)-r/2,q.alpha=0,f.addChild(q),createjs.Tween.get(q,{override:!1}).wait(1E3).to({alpha:0.5},
0).to({alpha:1,scaleX:e,scaleY:e,x:w,y:g},500).to({alpha:0,scaleX:s,scaleY:s,x:v,y:r},1500,createjs.Ease.sineOut).call(function(){f.removeChild(q);h(c,f)}))}var d=dotBox.utility,f=dotBox.views.Color,e=dotBox.views.constants,c=a.scalePixel(18),k=a.pixelSizes;if(d.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(d.isNullOrUndefined(b))throw Error("model is null or undefined.");a.observer.subscribe("gameOver",function(c){var d,f,k,l;l=0===c?1:0;d=b.gameConfig.playerNames[c];f=
b.gameConfig.playerNames[l];k=a.getPlayerColor(c);l=a.getPlayerColor(l);var r,s;s=new createjs.Container;r=new createjs.Shape;r.graphics.beginFill(e.BOARD_BACK_COLOR).drawRect(0,0,a.width(),a.height()-a.scalePixel(65));r.alpha=0.15;s.addChild(r);a.stage.addChild(s);createjs.Tween.get(r,{override:!0}).to({alpha:0.5},600,createjs.Ease.sineIn).call();h(c,s);g("=) "+d+" wins!",k,30);g("='(  Sorry "+f,l,4030)});return{}};dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.utility=dotBox.ai.utility||{};
(function(a){function b(a,b){return 3<=b.getLineStatesForBox(a).open.length}function g(a){var b=[],e,c;c=function(c){for(var e;e=c.next();)a.isLineConnected(e)||b.push(e)};e=h.hLineIterator(a.getDotCountLength(),a.getDotCountWidth());c(e);e=h.vLineIterator(a.getDotCountLength(),a.getDotCountWidth());c(e);return b}var l=dotBox.utility,h=dotBox.utility.iterators;a.findCloseableBoxes=function(a){var b=[],e,c=a.getBoxCount(),k;for(e=0;e<c;e++)a.isBoxScored(e)||(k=a.getLineStatesForBox(e),1===k.open.length&&
b.push({boxIndex:e,openLine:k.open[0]}));return b};a.boxHasThreeOrMoreOpen=b;a.getAllOpenLines=g;a.findNonThirdSideLines=function(a){var f,e,c,k,h=a.getDotCountLength(),n=a.getDotCountWidth(),p=[],x;e=g(a);x=function(c){return b(c,a)};for(f=0;f<e.length;f++)k=e[f],c=l.line.getBoxesFromLine(k,h,n),c.every(x)&&p.push(k);return p}})(dotBox.ai.utility);dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.AiPlayer=function AiPlayer(b,g){if(!(this instanceof AiPlayer))return AiPlayer.apply(new AiPlayer,arguments);this.playerIndex=b;this.gameEngine=g};
dotBox.ai.AiPlayer.prototype=function(){var a=dotBox.utility;return{getRandomDot:function(){var b,g;b=a.getRandom(0,this.gameEngine.getDotCountLength()-1);g=a.getRandom(0,this.gameEngine.getDotCountWidth()-1);return{x:b,y:g}},getRandomOpenLine:function(){var b=null;if(this.gameEngine.isGameOver())return null;for(;null===b;)b=this.getRandomDot(),b=this.gameEngine.getOpenLinesForDot(b),null!==b&&0===b.length&&(b=null);return a.getRandomItem(b)},move:function(){return this.getRandomOpenLine()},makeMove:function(a){var g=
this;if(void 0===a)return this.move();setTimeout(function(){a(g.move())},10)}}}();dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.AvoidThirdSide=function(){var a=dotBox.utility,b=dotBox.ai.utility,g;g=function h(a,b){if(!(this instanceof h))return h.apply(new h,arguments);this.playerIndex=a;this.gameEngine=b};a.inherit(g,dotBox.ai.AiPlayer);g.prototype.move=function(){var h;h=b.findNonThirdSideLines(this.gameEngine);return 0<h.length?h=a.getRandomItem(h):g.uber.move.apply(this)};return g}();dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.SingleBoxCloser=function(){var a=dotBox.utility,b;b=function l(a,b){if(!(this instanceof l))return l.apply(new l,arguments);this.playerIndex=a;this.gameEngine=b};a.inherit(b,dotBox.ai.AvoidThirdSide);b.prototype.move=function(){var l;l=dotBox.ai.utility.findCloseableBoxes(this.gameEngine);return 0<l.length?(l=a.getRandomItem(l),l.openLine):b.uber.move.apply(this)};return b}();dotBox=dotBox||{};
dotBox.controller=function(a,b){function g(c,g){var n,p,x,w;x=f.getCurrentPlayer();p={d1:c,d2:g};n=f.connectLine(p);w=0<n.boxesScored.length;e.selectedDot=null;e.hoveredDot=null;a.publish("view.lineConnected",p,w);n=n.boxesScored;var r;if(0<n.length){w=[];for(p=0;p<n.length;p++)r=n[p],w.push({box:r,lines:d.line.getLinesFromBox(r,f.getDotCountLength())});a.publish("view.boxesScored",w,x)}f.isGameOver()?a.publish("gameOver",l()):(n=f.getCurrentPlayer(),null!==n&&n!==x&&a.publish("views.playerTurnChanged"),!e.isQuickStarting&&
b.useAi&&1===n&&h(n))}function l(){var a,b=0,c=0,d;d=e.getCurrentScores();for(a=0;a<d.length;a++)d[a]>=c&&(c=d[a],b=a);return b}function h(b){a.publish("startRemoteTurn",b);c.makeMove(function(c){a.publish("endRemoteTurn",b,c)})}var d=dotBox.utility,f,e=null,c;f=dotBox.gameEngine({dotCountLength:b.dotColCount,dotCountWidth:b.dotRowCount});(function(){var a=[];d.isNullOrUndefined(b.playerNames)&&(b.playerNames=[]);1>b.playerNames.length||d.isNullOrUndefined(b.playerNames[0])||0===b.playerNames[0].length?
a.push("PLAYER 1"):a.push(b.playerNames[0]);2>b.playerNames.length||d.isNullOrUndefined(b.playerNames[1])||0===b.playerNames[1].length?b.useAi?a.push("HAL9000"):a.push("PLAYER 2"):a.push(b.playerNames[1]);b.playerNames=a})();b.useAi&&(c=new dotBox.ai.SingleBoxCloser(1,f));e=dotBox.model(f,b);a.subscribe("dotRollOver",function(b){f.hasAnyOpenLines(b)&&(e.hoveredDot=b,a.publish("view.dotRollOver",b))});a.subscribe("dotRollOut",function(b){e.hoveredDot=null;a.publish("view.dotRollOut",b)});a.subscribe("dotClick",
function(b){var c=e.selectedDot;if(!f.hasAnyOpenLines(b))return null;e.isSelectedDot(b)?(e.selectedDot=null,a.publish("view.dotSelectionChanged",c,null)):null!==e.selectedDot&&e.canConnectDots(b)?g(c,b):(e.selectedDot=b,a.publish("view.dotSelectionChanged",c,b))});return{startGame:function(){a.publish("startGame",e);if(!d.isNullOrUndefined(b.preMovePercent)){var c=b.preMovePercent,l,n;if(0>c||1<c)throw Error("percent must be between 0 and 1");if(0!==c){l=f.getTotalLineCount();l=Math.floor(l*c);0<
l&&(e.isQuickStarting=!0);for(var p=new dotBox.ai.AvoidThirdSide(-1,f),c=0;c<l;c++)n=p.move(),g(n.d1,n.d2);e.isQuickStarting=!1;c=f.getCurrentPlayer();b.useAi&&1===c&&h(f.getCurrentPlayer())}}},model:e}};dotBox=dotBox||{};dotBox.game=function(a,b){var g,l,h=[],d,f;g=new Observer;l=dotBox.views.viewContext(g,window.devicePixelRatio,2);d=dotBox.controller(g,b);f=d.model;h.push(dotBox.views.board(l,f));h.push(dotBox.views.score(l,f));h.push(dotBox.views.gameOver(l,f));l.initCanvasStage(function(a){if(a instanceof jQuery)return $(a[0]);"string"===typeof a&&0!==a.lastIndexOf("#",0)&&(a="#"+a);return $(a)}(a));d.startGame();return{stopGame:function(){g.publish("stopGame")}}};
(function(a){a.fn.dotBox=function(a){return dotBox.game(this,a)}})(jQuery); //@ sourceMappingURL=./dotBox-min.js.map
