var Observer=function(){function a(a,c){return c.priority-a.priority}function c(a){return void 0===a?!0:null===a}var g;g=function d(){if(!(this instanceof d))return new d;this._channelSubscribers={}};g.prototype.subscribe=function(d,k,f){var e=this._channelSubscribers[d];c(e)&&(e=[]);if(c(f)){f=e;var b,h,m=0;if(!c(f))for(h=f.length,b=0;b<h;b++)0>f[b].priority&&f[b].priority<m&&(m=f[b].priority);f=m-1}e.push({priority:f,callback:k});e=e.sort(a);this._channelSubscribers[d]=e};g.prototype.unsubscribe=
function(a,k){var f,e=this._channelSubscribers[a];if(!c(e)){for(f=0;f<e.length;f++)if(e[f].callback===k){e.splice(f,1);break}0===e.length&&delete this._channelSubscribers[a]}};g.prototype.publish=function(a,k,f,e){var b,h,m,g=null;if(0===arguments.length||c(a))throw Error("channelId argument required.");1<arguments.length&&(g=Array.prototype.slice.call(arguments,1));m=this._channelSubscribers[a];h={channelId:a,cancel:!1};if(c(m))return!0;for(b=0;b<m.length;b++)if(m[b].callback.apply(h,g),h.cancel)return!1;
return!0};return g}();var dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};
(function(a){function c(a){return void 0===a?!0:null===a}a.isNullOrUndefined=c;a.areSameDot=function(a,l){return c(a)&&c(l)?!0:c(a)!==c(l)?!1:a.x===l.x&&a.y===l.y};a.getRandom=function(a,c){return a+Math.floor(Math.random()*(c-a+1))};a.getRandomItem=function(c){var l;l=a.getRandom(0,c.length-1);return c[l]};a.inherit=function(){var a=function(){};return function(c,d){a.prototype=d.prototype;c.prototype=new a;c.uber=d.prototype;c.prototype.constructor=c}}()})(dotBox.utility);dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};dotBox.utility.line=dotBox.utility.line||{};
(function(a){function c(a){return 0<Math.abs(a.d1.x-a.d2.x)}a.isHLine=c;a.getBoxesFromLine=function(a,l,d){var k=l-1,f=[],e,b;c(a)?(e=a.d1.y,b=Math.min(a.d1.x,a.d2.x),0!==a.d1.y&&(a.d1.y!==d-1&&f.push(e*k+b),e-=1)):(b=a.d1.x,e=Math.min(a.d1.y,a.d2.y),0!==a.d1.x&&(a.d1.x!==l-1&&f.push(e*k+b),b-=1));f.push(e*k+b);return f};a.getLinesFromBox=function(a,c){var d=c-1,k=[],f;f=a%d;d=(a-f)/d;k.push({d1:{x:f,y:d},d2:{x:f+1,y:d}});k.push({d1:{x:f+1,y:d},d2:{x:f+1,y:d+1}});k.push({d1:{x:f,y:d+1},d2:{x:f+1,
y:d+1}});k.push({d1:{x:f,y:d},d2:{x:f,y:d+1}});return k}})(dotBox.utility.line);dotBox=dotBox||{};dotBox.utility=dotBox.utility||{};dotBox.utility.iterators=dotBox.utility.iterators||{};
(function(a){a.hLineIterator=function(a,g){function l(){return f?!1:{d1:{x:d,y:k},d2:{x:d+1,y:k}}}var d=-1,k=0,f=!1;return{next:function(){if(f)return null;if(k===g-1&&d===a-2)return f=!0,null;d===a-2?(k+=1,d=0):d+=1;return l()},current:l}};a.vLineIterator=function(a,g){function l(){return f?!1:{d1:{x:d,y:k},d2:{x:d,y:k+1}}}var d=-1,k=0,f=!1;return{next:function(){if(f)return null;if(k===g-2&&d===a-1)return f=!0,null;d===a-1?(k+=1,d=0):d+=1;return l()},current:l}}})(dotBox.utility.iterators);dotBox=dotBox||{};
dotBox.boxState=function(a,c){function g(){return f.length}function l(a){var b=g();if(0>a)throw new RangeError("boxIndex must be greater or equal to 0.");if(a>=b)throw new RangeError("boxIndex must be less than the box count ("+b+").");}function d(a){l(a);return null!==f[a]}function k(a){l(a);return f[a]}var f;(function(a,b){var h,m=(a-1)*(b-1);f=[];for(h=0;h<m;h++)f[h]=null})(a,c);return{getBoxCount:g,areAllBoxesScored:function(){return f.every(function(a){return null!==a})},isBoxScored:d,isBoxNotScored:function(a){return!d(a)},
whichPlayerScoredBox:k,scoreBox:function(a,b){l(a);f[a]=b},getCurrentScores:function(a){var b,h=[],m;for(b=0;b<a;b++)h[b]=0;a=g();for(b=0;b<a;b++)d(b)&&(m=k(b),h[m]+=1);return h},getPlayerBoxes:function(a){var b,h,m=[],c;h=g();for(b=0;b<h;b++)c=k(b),c===a&&m.push(b);return m}}};dotBox=dotBox||{};
dotBox.lineState=function(a,c){function g(b,h){var m,c;if(d.isNullOrUndefined(b))throw Error("line is null or undefined");l(b.d1,"line.d1");l(b.d2,"line.d2");c=Math.abs(b.d1.x-b.d2.x);m=Math.abs(b.d1.y-b.d2.y);if(1<c)throw new RangeError("Move appears to be too long on x-axis.  Line must only connect adjacent points.");if(1<m)throw new RangeError("Move appears to be too long on y-axis.  Line must only connect adjacent points.");if(1<c+m)throw new RangeError("Movement appears to be diagonal this is not allowed.");var e;
d.line.isHLine(b)?(c=k,m=b.d1.y,e=Math.min(b.d1.x,b.d2.x),m=m*(a-1)+e):(c=f,m=Math.min(b.d1.y,b.d2.y),e=b.d1.x,m=m*a+e);d.isNullOrUndefined(h)||h&&(c[m]=!0);return c[m]}function l(b,h){if(d.isNullOrUndefined(b))throw Error(h+" is null or undefined.");if(0>b.x)throw new RangeError(h+".x must be > 0.");if(b.x>=a)throw new RangeError(h+".x must be < "+a);if(0>b.y)throw new RangeError(h+".y must be > 0.");if(b.y>=c)throw new RangeError(h+".y must be < "+c);}var d=dotBox.utility,k=[],f=[],e;e={connected:g,
isBoxClosed:function(b){var h;h=d.line.getLinesFromBox(b,a);for(b=0;4>b;b++)if(!g(h[b]))return!1;return!0},getAllLinesForDot:function(b){var h=[],m,f;m=function(){return{x:b.x,y:b.y}};f=function(a,b){h.push({d1:m(),d2:{x:a,y:b}})};0<b.y&&f(b.x,b.y-1);b.x<a-1&&f(b.x+1,b.y);b.y<c-1&&f(b.x,b.y+1);0<b.x&&f(b.x-1,b.y);return h},getOpenLinesForDot:function(a){return e.getAllLinesForDot(a).filter(function(a){return!e.connected(a)})},getTotalLineCount:function(){return f.length+k.length},getLineStatesForBox:function(b){var h=
[],c=[],f,k;b=dotBox.utility.line.getLinesFromBox(b,a);for(f=0;4>f;f++)k=b[f],e.connected(k)?c.push(k):h.push(k);return{open:h,closed:c}}};(function(a,h){var c,e,d;e=(a-1)*h;d=(h-1)*a;for(c=0;c<e;c++)k[c]=!1;for(c=0;c<d;c++)f[c]=!1})(a,c);return e};dotBox=dotBox||{};
dotBox.gameEngine=function(a){function c(){return g()?null:h}function g(){return n.areAllBoxesScored()}var l=dotBox.utility,d,k,f,e,b,h,m,n=null;(function(a){a||(a={});k=l.isNullOrUndefined(a.dotCountLength)?10:parseInt(a.dotCountLength,10);f=l.isNullOrUndefined(a.dotCountWidth)?10:parseInt(a.dotCountWidth,10);d=l.isNullOrUndefined(a.playerCount)?2:parseInt(a.playerCount,10);h=l.isNullOrUndefined(a.startPlayer)?0:parseInt(a.startPlayer,10);if(isNaN(k))throw new TypeError("dotCountLength is not a number.");if(isNaN(f))throw new TypeError("dotCountWidth is not a number.");
if(isNaN(d))throw new TypeError("playerCount is not a number.");if(isNaN(h))throw new TypeError("startPlayer is not a number.");if(3>k)throw new RangeError("dotCountLength must be three or more");if(3>f)throw new RangeError("dotCountWidth must be three or more");if(2>d)throw new RangeError("playerCount must two or more");if(0>h||h>=d)throw new RangeError("startPlayer must be between 0 and playerCount-1");e=k-1;b=f-1;n=l.isNullOrUndefined(a.boxState)?dotBox.boxState(k,f):a.boxState;m=l.isNullOrUndefined(a.lineState)?
dotBox.lineState(k,f):a.lineState})(a);return{getDotCountLength:function(){return k},getBoxCountLength:function(){return e},getDotCountWidth:function(){return f},getBoxCountWidth:function(){return b},getBoxCount:function(){return e*b},getPlayerCount:function(){return d},getCurrentPlayer:c,getCurrentScores:function(){return n.getCurrentScores(d)},isLineConnected:function(a){return m.connected(a)},connectLine:function(a){var b={},e;if(g())throw Error("Cannot make a move when the game is over.");if(m.connected(a))throw Error("This line is already connected.");
e=c();m.connected(a,!0);a=l.line.getBoxesFromLine(a,k,f).filter(m.isBoxClosed).filter(n.isBoxNotScored);a.forEach(function(a){n.scoreBox(a,e)});b.boxesScored=a;b.gameOver=g();0===b.boxesScored.length?(a=g()?null:h=h===d-1?0:h+1,b.nextPlayer=a):b.nextPlayer=c();return b},isGameOver:g,hasAnyOpenLines:function(a){if(void 0===a)throw Error("dot argument was not supplied.");if(null===a)throw Error("dot argument was null.");return 0<m.getOpenLinesForDot(a).length},canConnectDots:function(a,h){var c,b,f;
if(l.isNullOrUndefined(a))throw Error("dot1 argument was null or undefined.");if(l.isNullOrUndefined(h))throw Error("dot2 argument was null or undefined.");b=m.getOpenLinesForDot(a);for(c=0;c<b.length;c++)if(f=b[c].d2,l.areSameDot(f,h))return!0;return!1},getPlayerBoxes:function(){return n.getPlayerBoxes.apply(n,arguments)},getOpenLinesForDot:function(){return m.getOpenLinesForDot.apply(m,arguments)},getTotalLineCount:function(){return m.getTotalLineCount.apply(m,arguments)},isBoxScored:function(){return n.isBoxScored.apply(n,
arguments)},getLineStatesForBox:function(){return m.getLineStatesForBox.apply(m,arguments)}}};dotBox=dotBox||{};
dotBox.model=function(a,c){var g=dotBox.utility,l;return l={selectedDot:null,hoveredDot:null,isSelectedDot:function(a){return null!==l.selectedDot&&g.areSameDot(a,l.selectedDot)},isHoveredDot:function(a){return null!==l.hoveredDot&&g.areSameDot(a,l.hoveredDot)},getDotColCount:function(){return a.getDotCountLength()},canConnectDots:function(c){return null!==l.selectedDot&&a.canConnectDots(l.selectedDot,c)},getDotRowCount:function(){return a.getDotCountWidth()},hasAnyOpenLines:function(c){return a.hasAnyOpenLines(c)},getCurrentScores:function(){return a.getCurrentScores()},
getCurrentPlayer:function(){return a.getCurrentPlayer()},getPlayerBoxes:function(){return a.getPlayerBoxes.apply(a,arguments)},gameConfig:c,isQuickStarting:!1}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};dotBox.views.constants={P1_COLOR:"#A4E402",P2_COLOR:"#BF7AFF",PX_COLOR:"#5B5B5B",SCORE_TXT_COLOR:"#E7F8F2",BOARD_BACK_COLOR:"#272822"};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.viewContext=function(a,c,g){var l,d;function k(a){for(var b in a)a.hasOwnProperty(b)&&(a[b]=a[b]*c*g);return a}var f=dotBox.utility,e,b;if(f.isNullOrUndefined(a))throw Error("observer parameter is required.");if(f.isNullOrUndefined(c))throw Error("pixelRatio is required.");d=l=0;b=k({DOT_RADIUS:5,DOT_MARGIN:20,POINT_FONT_SIZE:13,SCORE_BOARD_HEIGHT:65});a.subscribe("view.reserveCanvasSize",function(a){f.isNullOrUndefined(a)||(f.isNullOrUndefined(a.height)||(l+=a.height),f.isNullOrUndefined(a.width)||
(d+=a.width))});return e={observer:a,pixelRatio:c,stage:null,boxShapes:{},pixelSizes:b,initCanvasStage:function(a){var b;b=0;for(var f=null,k,g;null===f;)k="dotBoxCanvas_"+b,g=$("#"+k),0===g.length&&(f=k),b+=1;b=f;a.append('<canvas id="'+b+'" width='+d+" height="+l+' style="width: '+1/c*d+"px; height: "+1/c*l+'px;"></canvas>');e.stage=new createjs.Stage(b)},scalePixel:function(a){return a*c*g},scaleAllPixelProps:k,setDrawColors:function(a){var b=a.fillColor;a=a.strokeColor;dotBox.utility.isNullOrUndefined(b)||
(this.fillStyle=b.toString());dotBox.utility.isNullOrUndefined(a)||(this.strokeStyle=a.toString())},width:function(){if(null===e.stage)throw Error("stage has not been initialized; call initCanvasStage first.");return e.stage.canvas.width},height:function(){if(null===e.stage)throw Error("stage has not been initialized; call initCanvasStage first.");return e.stage.canvas.height},getPlayerColor:function(a){switch(a){case 0:return dotBox.views.constants.P1_COLOR;case 1:return dotBox.views.constants.P2_COLOR;
default:return dotBox.views.constants.PX_COLOR}}}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.Color=function(){function a(a){var c,e,b;c=parseInt(a.slice(1,3),16);e=parseInt(a.slice(3,5),16);a=parseInt(a.slice(5,7),16);b=new d;b.red=c;b.green=e;b.blue=a;return b}function c(a){var c,e,b,h;a=a.trim();a=a.toLowerCase();a=a.slice(5,a.length-1);a=a.trim();b=a.split(",");if(4!==b.length)throw Error("Could not parse rgba() color string.");a=parseInt(b[0].trim(),10);c=parseInt(b[1].trim(),10);e=parseInt(b[2].trim(),10);b=parseFloat(b[3].trim());h=new d;h.red=a;h.green=c;h.blue=e;h.alpha=
b;return h}function g(a){var c,e,b;a=a.trim();a=a.toLowerCase();a=a.slice(4,a.length-1);a=a.trim();e=a.split(",");if(3!==e.length)throw Error("Could not parse rgb() color string.");a=parseInt(e[0].trim(),10);c=parseInt(e[1].trim(),10);e=parseInt(e[2].trim(),10);b=new d;b.red=a;b.green=c;b.blue=e;return b}function l(d){d=d.trim();if(0===d.lastIndexOf("#",0)&&7===d.length)return a(d);if(0===d.lastIndexOf("rgba(",0))return c(d);if(0===d.lastIndexOf("rgb(",0))return g(d);throw Error("Invalid arguments.");
}var d;d=function f(a){var c;if(!(this instanceof f))return f.apply(new f,arguments);this.green=this.blue=this.red=255;this.alpha=1;if(1===arguments.length)return c=a.toString(),l(c);if(4===arguments.length){var h=arguments,m,g,r;c=Math.round(parseFloat(h[0]));m=Math.round(parseFloat(h[1]));g=Math.round(parseFloat(h[2]));r=parseFloat(h[3]);h=new d;h.red=c;h.green=m;h.blue=g;h.alpha=r;return h}if(3===arguments.length)return g=arguments,c=Math.round(parseFloat(g[0])),m=Math.round(parseFloat(g[1])),
h=Math.round(parseFloat(g[2])),g=new d,g.red=c,g.green=m,g.blue=h,g;if(0!==arguments.length)throw Error(arguments.length+" number of arguments not supported.");};d.parseHexColorString=a;d.parseColorString=l;d.parseRgbaColorString=c;d.parseRgbColorString=g;d.prototype.toString=function(){var a,c,b;a=Math.round(this.red);c=Math.round(this.green);b=Math.round(this.blue);return"rgba("+[a,c,b,this.alpha].join()+")"};d.prototype.clone=function(){var a=new d;a.red=this.red;a.green=this.green;a.blue=this.blue;
a.alpha=this.alpha;return a};return d}();dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.board=function(a,c){function g(c){u.isNullOrUndefined(c)||a.observer.publish("dotRollOver",c)}function l(c){u.isNullOrUndefined(c)||a.observer.publish("dotRollOut",c)}function d(){B||k(this.dot)}function k(c){a.observer.publish("dotClick",c)}function f(){var a=E,b=p(2.5*t.DOT_RADIUS);u.areSameDot(a,b)||(B||(!u.isNullOrUndefined(b)&&c.hasAnyOpenLines(b)?e("pointer"):e("")),E=b,B||(l(a),g(b)))}function e(c){a.stage.canvas.style.cursor=c}function b(){a.stage.update()}function h(b){var h,
f;b instanceof createjs.Shape?(h=b,b=h.dot,f=!0):(h=m(b),f=!1);b=c.isSelectedDot(b)?H:c.isHoveredDot(b)&&c.canConnectDots(b)?C:c.isHoveredDot(b)?I:J;b=new F(b);f?(h.fillColor=b,h.graphics.beginFill(b).inject(a.setDrawColors,h).drawCircle(0,0,t.DOT_RADIUS).endFill()):createjs.Tween.get(h.fillColor,{override:!0}).to(b,250);return h}function m(a){return D[a.y][a.x]}function n(b,h,f){var e,d=m(b.d1),k=m(b.d2),g=!1,l=a.scalePixel(1),n=null,t;e=q(b);u.isNullOrUndefined(e)?(e=new createjs.Shape,w(b,e),g=
!0):e.graphics.clear();e.graphics.setStrokeStyle(l).beginStroke(h).moveTo(d.x,d.y).lineTo(k.x,k.y);t=c.isQuickStarting;g&&(y.isHLine(b)?(e.scaleX=0.1,e.x=d.x-0.1*d.x,n={scaleX:1,x:0}):(e.scaleY=0.1,e.y=d.y-0.1*d.y,n={scaleY:1,y:0}),e.on("click",r),a.stage.addChild(e),createjs.Tween.get(e,{override:!0}).to(n,300).call(function(){var c;t||f||(c=new createjs.Shape,c.graphics.setStrokeStyle(a.scalePixel(1)).beginStroke(A).drawCircle(0,0,a.pixelSizes.DOT_RADIUS),c.x=k.x,c.y=k.y,c.scaleX=0,c.scaleY=0,a.stage.addChild(c),
createjs.Tween.get(c).to({scaleX:1.5,scaleY:1.5},150).to({scaleX:5,scaleY:5,alpha:0},1E3,createjs.Ease.sineOut).call(function(){a.stage.removeChild(c)}))}))}function r(c){c=a.stage.getObjectsUnderPoint(c.stageX,c.stageY).filter(function(a){return!u.isNullOrUndefined(a.dot)});0<c.length&&d.apply(c[0])}function x(b,h){var f,e,d,k;c.isQuickStarting||(e=m(b.lines[0].d1),k=m(b.lines[0].d2),f=e.x+(k.x-e.x)/2,e=m(b.lines[1].d1),k=m(b.lines[1].d2),e=e.y+(k.y-e.y)/2,d=new createjs.Text("+"+h,t.POINT_FONT_SIZE+
"px Helvetica",G.SCORE_TXT_COLOR),d.x=f,d.y=e,d.textAlign="center",d.textBaseline="middle",d.alpha=0,a.stage.addChild(d),createjs.Tween.get(d,{override:!1}).wait(550).to({alpha:1},0).to({alpha:0,y:a.height()+a.scalePixel(50)},3E3,createjs.Ease.sineOut).call(function(){a.stage.removeChild(d)}),createjs.Tween.get(d,{override:!1}).wait(550).to({scaleX:1.5,scaleY:1.5},200,createjs.Ease.elasticInOut))}function w(a,c){var b,h;b=s(a);h=b.store[b.y];u.isNullOrUndefined(h)&&(h={},b.store[b.y]=h);h[b.x]=c}
function q(a){var c;a=s(a);if(!a.store.hasOwnProperty(a.y))return null;c=a.store[a.y];return c.hasOwnProperty(a.x)?c[a.x]:null}function s(a){var c,b;u.line.isHLine(a)?(b=K,c=a.d1.y,a=Math.min(a.d1.x,a.d2.x)):(b=L,c=Math.min(a.d1.y,a.d2.y),a=a.d1.x);return{x:a,y:c,store:b}}function v(a,c){var b;b=Math.floor((a-t.DOT_MARGIN/2)/(2*t.DOT_RADIUS+t.DOT_MARGIN));return 0>b||b>=c?null:b}function p(b){var h,e,f,d;h=a.stage.mouseX;e=a.stage.mouseY;if(!a.stage.mouseInBounds)return null;f=v(h,c.getDotColCount());
if(null===f)return null;d=v(e,c.getDotRowCount());if(null===d)return null;f={x:f,y:d};d=m(f);var k=d.y;h=Math.pow(d.x-h,2)+Math.pow(k-e,2);b=Math.pow(b,2);h<=b||(f=null);return f}var u=dotBox.utility,y=dotBox.utility.line,G=dotBox.views.constants,F=dotBox.views.Color;if(u.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(u.isNullOrUndefined(c))throw Error("model is null or undefined.");var t=a.pixelSizes,J="#53d2f1",I="#89E0F5",H="#fc1f70",C="#E20355",A="white",D,K={},L={},
z,E=null,B=!1;(function(){var b,h,f;b={height:0,width:0};h=2*c.getDotColCount()*t.DOT_RADIUS;f=(c.getDotColCount()+1)*t.DOT_MARGIN;b.width=h+f;h=2*c.getDotRowCount()*t.DOT_RADIUS;f=(c.getDotRowCount()+1)*t.DOT_MARGIN;b.height=h+f;a.observer.publish("view.reserveCanvasSize",b)})();a.observer.subscribe("startGame",function(){var e,m,k,g=c.getDotRowCount(),l=c.getDotColCount(),n;e=new createjs.Shape;e.graphics.beginFill(G.BOARD_BACK_COLOR).drawRect(0,0,a.width(),a.height());a.stage.addChild(e);D=[];
for(m=0;m<g;m++)for(e=0;e<l;e++)0===e&&(n=[],D.push(n)),k=new createjs.Shape,k.dot={x:e,y:m},h(k),k.x=e*(t.DOT_MARGIN+2*t.DOT_RADIUS)+(t.DOT_MARGIN+t.DOT_RADIUS),k.y=m*(t.DOT_MARGIN+2*t.DOT_RADIUS)+(t.DOT_MARGIN+t.DOT_RADIUS),k.on("click",d),n.push(k),a.stage.addChild(k);a.stage.update();a:{g=20;z&&(clearInterval(z),z=null);if(null===g)g=20;else if(0>=g)break a;z=setInterval(f,1E3/Math.min(50,g))}createjs.Ticker.addEventListener("tick",b);createjs.Ticker.setFPS(60)});a.observer.subscribe("view.dotRollOver",
function(a){a=h(a);createjs.Tween.get(a,{override:!0}).to({scaleX:2,scaleY:2},150)});a.observer.subscribe("view.dotRollOut",function(a){a=h(a);createjs.Tween.get(a,{override:!0}).to({scaleX:1,scaleY:1},150)});a.observer.subscribe("view.dotSelectionChanged",function(a,b){var c;null!==a&&h(a);null!==b&&h(b);a!==b&&(c=m(null!==b?b:a),createjs.Tween.get(c,{override:!0}).to({scaleX:1,scaleY:1},150).call(function(){var a=p(t.DOT_RADIUS);u.isNullOrUndefined(a)&&e("")}))});a.observer.subscribe("view.lineConnected",
function(a,b){var c;h(a.d1);c=h(a.d2);createjs.Tween.get(c,{override:!0}).to({scaleX:1,scaleY:1},150);n(a,A,b)});a.observer.subscribe("view.boxesScored",function(b,c){var h;for(h=0;h<b.length;h++){var e=b[h],f=c,d=void 0,k=void 0,g=d=void 0,l=void 0,n=void 0,t=void 0,g=void 0,y=a.scalePixel(10),p=a.scalePixel(1),t=a.getPlayerColor(f),n=new F(t);n.alpha=0.33;n=n.toString();k=m(e.lines[0].d1);d=m(e.lines[1].d2);g=d.x-k.x;l=d.y-k.y;d=new createjs.Shape;d.graphics.setStrokeStyle(p).beginStroke(t).beginFill(n).drawRect(k.x,
k.y,g,l);g=(g+y)/g;d.scaleX=g;d.scaleY=g;d.x=-1*(k.x*g-k.x)-y/2;d.y=-1*(k.y*g-k.y)-y/2;d.upperLeft={x:k.x,y:k.y};d.alpha=0;d.on("click",r);a.stage.addChild(d);a.boxShapes[e.box]=d;createjs.Tween.get(d,{override:!0}).wait(350).to({alpha:1},0).to({x:0,y:0,scaleX:1,scaleY:1},350)}x(b[0],b.length)});a.observer.subscribe("startRemoteTurn",function(a){e("wait");B=!0});a.observer.subscribe("endRemoteTurn",function(a,b){var c=u.getRandom(700,1250),h=u.getRandom(170,750),d=u.getRandom(500,750),f=u.getRandom(Math.floor(75),
750);setTimeout(function(){g(b.d1);setTimeout(function(){k(b.d1);l(b.d1);setTimeout(function(){g(b.d2);setTimeout(function(){B=!1;e(null);k(b.d2);l(b.d2)},f)},d)},h)},c)});a.observer.subscribe("stopGame",function(){createjs.Ticker.removeEventListener("tick",b);z&&(clearInterval(z),z=null)});return{}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.score=function(a,c){function g(c,d){var k=new createjs.Container,g,l=a.scalePixel(1),w=a.scalePixel(2),u=a.scalePixel(9),C=a.scalePixel(6),A=a.scalePixel(13);g=new createjs.Shape;g.graphics.setStrokeStyle(l).beginStroke(x).beginFill(r).drawRoundRect(0,0,p.SCORE_BOX_W,d,w);k.addChild(g);g=new createjs.Text("0",p.SCORE_FONT_SIZE+"px Helvetica",f.SCORE_TXT_COLOR);g.x=p.SCORE_BOX_W/2;g.y=C+d/2;g.textAlign="center";g.textBaseline="middle";k.addChild(g);b.push(g);g=new createjs.Shape;g.graphics.setStrokeStyle(l).beginFill(q).beginStroke(s).arc(p.SCORE_BOX_W/
2,d+A,p.SCORE_BOX_W/4,Math.PI+0.25*Math.PI,1.75*Math.PI);g.alpha=0;h.push(g);k.addChild(g);l=g=new createjs.Shape;w=Math.round(0.3*d);C=a.scalePixel(2);A=a.scalePixel(2);l.fillColor=new e(v);l.strokeColor=new e(v);l.graphics.setStrokeStyle(C).beginStroke(v).beginFill(v).inject(a.setDrawColors,l).drawRoundRect(0,0,p.SCORE_BOX_W,w,A).endFill();k.addChild(g);m.push(g);g=new createjs.Text(c,p.P_NAME_FONT_SIZE+"px Helvetica",f.SCORE_TXT_COLOR);g.x=p.SCORE_BOX_W/2;g.y=u;g.textAlign="center";g.textBaseline=
"middle";n.push(g);k.addChild(g);return k}function l(a){var b,c,e,k,g;for(b=0;b<h.length;b++)c=h[b],b===a?(createjs.Tween.get(c,{override:!0}).to({alpha:1},250,createjs.Ease.sineIn),c=f.SCORE_TXT_COLOR):(createjs.Tween.get(c,{override:!0}).to({alpha:0},250,createjs.Ease.sineOut),c=w),g=m[b],e=d("fill",b,a),k=d("stroke",b,a),createjs.Tween.get(g.fillColor,{override:!0}).to(e,200),createjs.Tween.get(g.strokeColor,{override:!0}).to(k,200),n[b].color=c}function d(a,b,c){b===c?(b=0===b?new e(f.P1_COLOR):
new e(f.P2_COLOR),"fill"===a&&(b.alpha=0.33)):b=new e(v);return b}var k=dotBox.utility,f=dotBox.views.constants,e=dotBox.views.Color,b=[],h=[],m=[],n=[],r="#272822",x="#3b3d38",w="#a69b9d",q="#fc1f70",s="#E20355",v="#40403d",p=a.scaleAllPixelProps({SCORE_BOX_W:75,SCORE_FONT_SIZE:25,P_NAME_FONT_SIZE:10}),u=a.pixelSizes.SCORE_BOARD_HEIGHT;if(k.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(k.isNullOrUndefined(c))throw Error("model is null or undefined.");a.observer.publish("view.reserveCanvasSize",
{height:u});a.observer.subscribe("startGame",function(){var d,e,f=a.scalePixel(10);e=a.scalePixel(5);var k=u-2*e;d=a.height()-u;e=d+e+1;b=[];h=[];m=[];n=[];var r,x=a.scalePixel(1),w=a.height(),q=a.width();r=new createjs.Shape;r.graphics.beginLinearGradientFill(["#5b5b5b","#545454"],[0,1],0,d,0,w).drawRect(0,d,q,w).endFill();r.graphics.setStrokeStyle(x).beginStroke("#323232").moveTo(0,d).lineTo(q,d).endStroke();r.graphics.setStrokeStyle(x).beginStroke("#7d7d7d").moveTo(0,d+x).lineTo(q,d+x).endStroke();
a.stage.addChild(r);d=g(c.gameConfig.playerNames[0],k);d.x=f;d.y=e;a.stage.addChild(d);d=g(c.gameConfig.playerNames[1],k);d.x=a.width()-f-p.SCORE_BOX_W;d.y=e;a.stage.addChild(d);l(c.getCurrentPlayer())});a.observer.subscribe("gameOver",function(a){l(a)});a.observer.subscribe("view.boxesScored",function(){var a,d;d=c.getCurrentScores();for(a=0;a<d.length;a++)b[a].text=d[a]});a.observer.subscribe("views.playerTurnChanged",function(){l(c.getCurrentPlayer())});return{}};dotBox=dotBox||{};dotBox.views=dotBox.views||{};
dotBox.views.gameOver=function(a,c){function g(c,d,k){var g,l,q,s,v,p=a.scalePixel(10),u=a.scalePixel(2),y;g=new createjs.Container;q=a.height()-h.SCORE_BOARD_HEIGHT;s=a.width();l=new createjs.Text(c,b+"px Helvetica",e.SCORE_TXT_COLOR);l.textAlign="center";l.textBaseline="middle";v=l.getBounds();c=v.height+2*p+2*u;p=v.width+2*p+2*u;v=new createjs.Shape;v.graphics.beginFill(e.BOARD_BACK_COLOR).drawRect(0,0,p,c);g.addChild(v);y=new f(d);y.alpha=0.2;v=new createjs.Shape;v.graphics.setStrokeStyle(u).beginStroke(d).beginFill(y.toString()).drawRect(0,
0,p,c);g.addChild(v);l.x=p/2;l.y=c/2;g.addChild(l);g.x=s/2;g.y=q/2;d=(s-p)/2;q=(q-c)/2;g.alpha=0;g.scaleX=0;g.scaleY=0;a.stage.addChild(g);createjs.Tween.get(g,{override:!0}).wait(k).to({alpha:1,scaleX:1,scaleY:1,x:d,y:q},1E3,createjs.Ease.quadIn).wait(2500).to({x:s+p/2},500,createjs.Ease.quadOut).call(function(){a.stage.removeChild(g)})}function l(b,c,d){var h,e,g=a.scalePixel(1);b=a.boxShapes[b];e=a.getPlayerColor(c);h=new f(e);h.alpha=0.33;h=h.toString();c=new createjs.Shape;c.graphics.setStrokeStyle(g).beginStroke(e).beginFill(h).drawRect(b.upperLeft.x,
b.upperLeft.y,d,d);c.upperLeft={x:b.upperLeft.x,y:b.upperLeft.y};return c}function d(b,e){var f,g,w,q,s,v,p;f=c.getPlayerBoxes(b);0!==f.length&&(s=2*h.DOT_RADIUS+h.DOT_MARGIN,f=f[k.getRandom(0,f.length-1)],p=l(f,b,s),g=a.scalePixel(15),f=(s+g)/s,w=-1*(p.upperLeft.x*f-p.upperLeft.x)-g/2,g=-1*(p.upperLeft.y*f-p.upperLeft.y)-g/2,q=a.scalePixel(45),s=(s+q)/s,v=-1*(p.upperLeft.x*s-p.upperLeft.x)-q/2,q=-1*(p.upperLeft.y*s-p.upperLeft.y)-q/2,p.alpha=0,e.addChild(p),createjs.Tween.get(p,{override:!1}).wait(1E3).to({alpha:0.5},
0).to({alpha:1,scaleX:f,scaleY:f,x:w,y:g},500).to({alpha:0,scaleX:s,scaleY:s,x:v,y:q},1500,createjs.Ease.sineOut).call(function(){e.removeChild(p);d(b,e)}))}var k=dotBox.utility,f=dotBox.views.Color,e=dotBox.views.constants,b=a.scalePixel(18),h=a.pixelSizes;if(k.isNullOrUndefined(a))throw Error("viewContext is null or undefined.");if(k.isNullOrUndefined(c))throw Error("model is null or undefined.");a.observer.subscribe("gameOver",function(b){var h,f,k,l;l=0===b?1:0;h=c.gameConfig.playerNames[b];f=
c.gameConfig.playerNames[l];k=a.getPlayerColor(b);l=a.getPlayerColor(l);var q,s;s=new createjs.Container;q=new createjs.Shape;q.graphics.beginFill(e.BOARD_BACK_COLOR).drawRect(0,0,a.width(),a.height()-a.scalePixel(65));q.alpha=0.15;s.addChild(q);a.stage.addChild(s);createjs.Tween.get(q,{override:!0}).to({alpha:0.5},600,createjs.Ease.sineIn).call();d(b,s);g("=) "+h+" wins!",k,30);g("='(  Sorry "+f,l,4030)});return{}};dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.utility=dotBox.ai.utility||{};
(function(a){function c(a,c){return 3<=c.getLineStatesForBox(a).open.length}function g(a){var c=[],e,b;b=function(b){for(var d;d=b.next();)a.isLineConnected(d)||c.push(d)};e=d.hLineIterator(a.getDotCountLength(),a.getDotCountWidth());b(e);e=d.vLineIterator(a.getDotCountLength(),a.getDotCountWidth());b(e);return c}var l=dotBox.utility,d=dotBox.utility.iterators;a.findCloseableBoxes=function(a){var c=[],d,b=a.getBoxCount(),h;for(d=0;d<b;d++)a.isBoxScored(d)||(h=a.getLineStatesForBox(d),1===h.open.length&&
c.push({boxIndex:d,openLine:h.open[0]}));return c};a.boxHasThreeOrMoreOpen=c;a.getAllOpenLines=g;a.findNonThirdSideLines=function(a){var d,e,b,h,m=a.getDotCountLength(),n=a.getDotCountWidth(),r=[],x;e=g(a);x=function(b){return c(b,a)};for(d=0;d<e.length;d++)h=e[d],b=l.line.getBoxesFromLine(h,m,n),b.every(x)&&r.push(h);return r}})(dotBox.ai.utility);dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.AiPlayer=function AiPlayer(c,g){if(!(this instanceof AiPlayer))return AiPlayer.apply(new AiPlayer,arguments);this.playerIndex=c;this.gameEngine=g};
dotBox.ai.AiPlayer.prototype=function(){var a=dotBox.utility;return{getRandomDot:function(){var c,g;c=a.getRandom(0,this.gameEngine.getDotCountLength()-1);g=a.getRandom(0,this.gameEngine.getDotCountWidth()-1);return{x:c,y:g}},getRandomOpenLine:function(){var c=null;if(this.gameEngine.isGameOver())return null;for(;null===c;)c=this.getRandomDot(),c=this.gameEngine.getOpenLinesForDot(c),null!==c&&0===c.length&&(c=null);return a.getRandomItem(c)},move:function(){return this.getRandomOpenLine()},makeMove:function(a){var g=
this;if(void 0===a)return this.move();setTimeout(function(){a(g.move())},10)}}}();dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.AvoidThirdSide=function(){var a=dotBox.utility,c=dotBox.ai.utility,g;g=function d(a,c){if(!(this instanceof d))return d.apply(new d,arguments);this.playerIndex=a;this.gameEngine=c};a.inherit(g,dotBox.ai.AiPlayer);g.prototype.move=function(){var d;d=c.findNonThirdSideLines(this.gameEngine);return 0<d.length?d=a.getRandomItem(d):g.uber.move.apply(this)};return g}();dotBox=dotBox||{};dotBox.ai=dotBox.ai||{};dotBox.ai.SingleBoxCloser=function(){var a=dotBox.utility,c;c=function l(a,c){if(!(this instanceof l))return l.apply(new l,arguments);this.playerIndex=a;this.gameEngine=c};a.inherit(c,dotBox.ai.AvoidThirdSide);c.prototype.move=function(){var l;l=dotBox.ai.utility.findCloseableBoxes(this.gameEngine);return 0<l.length?(l=a.getRandomItem(l),l.openLine):c.uber.move.apply(this)};return c}();dotBox=dotBox||{};
dotBox.controller=function(a,c){function g(b,g){var n,r,x,w;x=f.getCurrentPlayer();r={d1:b,d2:g};n=f.connectLine(r);w=0<n.boxesScored.length;e.selectedDot=null;e.hoveredDot=null;a.publish("view.lineConnected",r,w);n=n.boxesScored;var q;if(0<n.length){w=[];for(r=0;r<n.length;r++)q=n[r],w.push({box:q,lines:k.line.getLinesFromBox(q,f.getDotCountLength())});a.publish("view.boxesScored",w,x)}f.isGameOver()?a.publish("gameOver",l()):(n=f.getCurrentPlayer(),null!==n&&n!==x&&a.publish("views.playerTurnChanged"),!e.isQuickStarting&&
c.useAi&&1===n&&d(n))}function l(){var a,b=0,c=0,d;d=e.getCurrentScores();for(a=0;a<d.length;a++)d[a]>=c&&(c=d[a],b=a);return b}function d(c){a.publish("startRemoteTurn",c);b.makeMove(function(b){a.publish("endRemoteTurn",c,b)})}var k=dotBox.utility,f,e=null,b;f=dotBox.gameEngine({dotCountLength:c.dotColCount,dotCountWidth:c.dotRowCount});(function(){var a=[];k.isNullOrUndefined(c.playerNames)&&(c.playerNames=[]);1>c.playerNames.length||k.isNullOrUndefined(c.playerNames[0])||0===c.playerNames[0].length?
a.push("PLAYER 1"):a.push(c.playerNames[0]);2>c.playerNames.length||k.isNullOrUndefined(c.playerNames[1])||0===c.playerNames[1].length?c.useAi?a.push("HAL9000"):a.push("PLAYER 2"):a.push(c.playerNames[1]);c.playerNames=a})();c.useAi&&(b=new dotBox.ai.SingleBoxCloser(1,f));e=dotBox.model(f,c);a.subscribe("dotRollOver",function(b){f.hasAnyOpenLines(b)&&(e.hoveredDot=b,a.publish("view.dotRollOver",b))});a.subscribe("dotRollOut",function(b){e.hoveredDot=null;a.publish("view.dotRollOut",b)});a.subscribe("dotClick",
function(b){var c=e.selectedDot;if(!f.hasAnyOpenLines(b))return null;e.isSelectedDot(b)?(e.selectedDot=null,a.publish("view.dotSelectionChanged",c,null)):null!==e.selectedDot&&e.canConnectDots(b)?g(c,b):(e.selectedDot=b,a.publish("view.dotSelectionChanged",c,b))});return{startGame:function(){a.publish("startGame",e);if(!k.isNullOrUndefined(c.preMovePercent)){var b=c.preMovePercent,l,n;if(0>b||1<b)throw Error("percent must be between 0 and 1");if(0!==b){l=f.getTotalLineCount();l=Math.floor(l*b);0<
l&&(e.isQuickStarting=!0);for(var r=new dotBox.ai.AvoidThirdSide(-1,f),b=0;b<l;b++)n=r.move(),g(n.d1,n.d2);e.isQuickStarting=!1;b=f.getCurrentPlayer();c.useAi&&1===b&&d(f.getCurrentPlayer())}}},model:e}};dotBox=dotBox||{};dotBox.game=function(a,c){var g,l,d=[],k,f;g=new Observer;l=dotBox.views.viewContext(g,window.devicePixelRatio,c.uiScale);k=dotBox.controller(g,c);f=k.model;d.push(dotBox.views.board(l,f));d.push(dotBox.views.score(l,f));d.push(dotBox.views.gameOver(l,f));l.initCanvasStage(function(a){if(a instanceof jQuery)return $(a[0]);"string"===typeof a&&0!==a.lastIndexOf("#",0)&&(a="#"+a);return $(a)}(a));k.startGame();return{stopGame:function(){g.publish("stopGame")}}};
(function(a){a.fn.dotBox=function(a){return dotBox.game(this,a)}})(jQuery); //@ sourceMappingURL=./dotBox-min.js.map
